name: Publish Package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # needed to use yarn v4
      - name: Enable corepack
        run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: |
          yarn install --immutable --check-cache
          run-s build postbuild
          yarn pack

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
